# permissions for end users to edit omsoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: http-operator
    app.kubernetes.io/managed-by: kustomize
  name: omsoperator-editor-role
rules:
- apiGroups:
  - whatnot.etamhof
  resources:
  - omsoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - whatnot.etamhof
  resources:
  - omsoperators/status
  verbs:
  - get
